# ref: https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  # すべてのlinterを無効化
  # 以下のlinterは無効化できないので、個別でdisableにする
  # errcheck, govet, ineffassign, staticcheck, unused
  default: none
  # 有効なlinterを設定 ref: https://golangci-lint.run/usage/linters/
  enable:
    - gosec
    - govet
    - staticcheck
  # 無効なlinterを設定
  disable: []
  # 特定の除外設定
  exclusions:
    # 自動生成ファイルを除外
    generated: lax
    # 事前定義された除外設定
    presets: []
    # パス・ルール・テキスト単位での除外設定
    rules: []
    # パス・ファイルごとの除外設定
    paths: []
formatters:
  # フォーマッタは、Go標準を利用するので無効化
  enable: []
# ref: https://golangci-lint.run/usage/configuration/#issues-configuration
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  uniq-by-line: true
  # HEADとの差分や新しいファイル等のみを検出対象とする
  new: true
  # 修正可能なlinterの問題を自動修正する
  fix: true
# ref: https://golangci-lint.run/usage/configuration/#run-configuration
run:
  timeout: 10m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 0
